apiVersion: v1
kind: Template
metadata:
  name: kafka-manager
  labels:
    app: kafka-manager
parameters:
- description: kafka-manager image to use
  displayName : Image name
  name: IMAGE_NAME
  value: registry.hub.docker.com/solsson/kafka-manager:latest
- description: zookeeper target
  displayName: Target name
  name: ZOOKEEPER_SERVICE
  value: zookeeper:2181
objects:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: kafka-manager
    labels: 
      app: kafka-manager
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: kafka-manager
      spec:
        containers:
        - name: kafka-manager
          image: ${IMAGE_NAME}
          imagePullPolicy: IfNotPresent
          env:
            name: ZK_HOSTS
            value: ${ZOOKEEPER_SERVICE}
          ports:
          - name: kafka-manager
            containerPort: 80
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: kafka-manager
    labels: 
      app: kafka-manager
  spec:
    ports:
    - name: kafka-manager
      port: 80
      targetPort: 80
      protocol: TCP
    selector:
      name: kafka-manager
    type: ClusterIP
